# ESO will sync these from AWS Secrets Manager to a Kubernetes Secret

# ExternalSecret for Catalog MySQL credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-db
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: catalog-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_CATALOG_PERSISTENCE_USER
      remoteRef:
        key: project-bedrock-catalog-db-credentials
        property: username
    - secretKey: RETAIL_CATALOG_PERSISTENCE_PASSWORD
      remoteRef:
        key: project-bedrock-catalog-db-credentials
        property: password
---
# ExternalSecret for Orders PostgreSQL credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-db
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: orders-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_ORDERS_PERSISTENCE_USERNAME
      remoteRef:
        key: project-bedrock-orders-db-credentials
        property: username
    - secretKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD
      remoteRef:
        key: project-bedrock-orders-db-credentials
        property: password
